export interface Country {
  label: string;
  value: string;
  flag: string;
  code: string;
}

export const countries: Country[] = [
  { label: "Afganistán", value: "AF", flag: "🇦🇫", code: "+93" },
  { label: "Albania", value: "AL", flag: "🇦🇱", code: "+355" },
  { label: "Alemania", value: "DE", flag: "🇩🇪", code: "+49" },
  { label: "Andorra", value: "AD", flag: "🇦🇩", code: "+376" },
  { label: "Angola", value: "AO", flag: "🇦🇴", code: "+244" },
  { label: "Antigua y Barbuda", value: "AG", flag: "🇦🇬", code: "+1-268" },
  { label: "Arabia Saudita", value: "SA", flag: "🇸🇦", code: "+966" },
  { label: "Argelia", value: "DZ", flag: "🇩🇿", code: "+213" },
  { label: "Argentina", value: "AR", flag: "🇦🇷", code: "+54" },
  { label: "Armenia", value: "AM", flag: "🇦🇲", code: "+374" },
  { label: "Australia", value: "AU", flag: "🇦🇺", code: "+61" },
  { label: "Austria", value: "AT", flag: "🇦🇹", code: "+43" },
  { label: "Azerbaiyán", value: "AZ", flag: "🇦🇿", code: "+994" },
  { label: "Bahamas", value: "BS", flag: "🇧🇸", code: "+1-242" },
  { label: "Bangladés", value: "BD", flag: "🇧🇩", code: "+880" },
  { label: "Barbados", value: "BB", flag: "🇧🇧", code: "+1-246" },
  { label: "Baréin", value: "BH", flag: "🇧🇭", code: "+973" },
  { label: "Belice", value: "BZ", flag: "🇧🇿", code: "+501" },
  { label: "Benín", value: "BJ", flag: "🇧🇯", code: "+229" },
  { label: "Bielorrusia", value: "BY", flag: "🇧🇾", code: "+375" },
  { label: "Birmania", value: "MM", flag: "🇲🇲", code: "+95" },
  { label: "Bolivia", value: "BO", flag: "🇧🇴", code: "+591" },
  { label: "Bosnia y Herzegovina", value: "BA", flag: "🇧🇦", code: "+387" },
  { label: "Botsuana", value: "BW", flag: "🇧🇼", code: "+267" },
  { label: "Brasil", value: "BR", flag: "🇧🇷", code: "+55" },
  { label: "Brunéi", value: "BN", flag: "🇧🇳", code: "+673" },
  { label: "Bulgaria", value: "BG", flag: "🇧🇬", code: "+359" },
  { label: "Burkina Faso", value: "BF", flag: "🇧🇫", code: "+226" },
  { label: "Burundi", value: "BI", flag: "🇧🇮", code: "+257" },
  { label: "Bután", value: "BT", flag: "🇧🇹", code: "+975" },
  { label: "Cabo Verde", value: "CV", flag: "🇨🇻", code: "+238" },
  { label: "Camboya", value: "KH", flag: "🇰🇭", code: "+855" },
  { label: "Camerún", value: "CM", flag: "🇨🇲", code: "+237" },
  { label: "Canadá", value: "CA", flag: "🇨🇦", code: "+1" },
  { label: "Catar", value: "QA", flag: "🇶🇦", code: "+974" },
  { label: "Chad", value: "TD", flag: "🇹🇩", code: "+235" },
  { label: "Chile", value: "CL", flag: "🇨🇱", code: "+56" },
  { label: "China", value: "CN", flag: "🇨🇳", code: "+86" },
  { label: "Chipre", value: "CY", flag: "🇨🇾", code: "+357" },
  { label: "Colombia", value: "CO", flag: "🇨🇴", code: "+57" },
  { label: "Comoras", value: "KM", flag: "🇰🇲", code: "+269" },
  { label: "Corea del Norte", value: "KP", flag: "🇰🇵", code: "+850" },
  { label: "Corea del Sur", value: "KR", flag: "🇰🇷", code: "+82" },
  { label: "Costa de Marfil", value: "CI", flag: "🇨🇮", code: "+225" },
  { label: "Costa Rica", value: "CR", flag: "🇨🇷", code: "+506" },
  { label: "Croacia", value: "HR", flag: "🇭🇷", code: "+385" },
  { label: "Cuba", value: "CU", flag: "🇨🇺", code: "+53" },
  { label: "Dinamarca", value: "DK", flag: "🇩🇰", code: "+45" },
  { label: "Dominica", value: "DM", flag: "🇩🇲", code: "+1-767" },
  { label: "Ecuador", value: "EC", flag: "🇪🇨", code: "+593" },
  { label: "Egipto", value: "EG", flag: "🇪🇬", code: "+20" },
  { label: "El Salvador", value: "SV", flag: "🇸🇻", code: "+503" },
  { label: "Emiratos Árabes Unidos", value: "AE", flag: "🇦🇪", code: "+971" },
  { label: "Eritrea", value: "ER", flag: "🇪🇷", code: "+291" },
  { label: "Eslovaquia", value: "SK", flag: "🇸🇰", code: "+421" },
  { label: "Eslovenia", value: "SI", flag: "🇸🇮", code: "+386" },
  { label: "España", value: "ES", flag: "🇪🇸", code: "+34" },
  { label: "Estados Unidos", value: "US", flag: "🇺🇸", code: "+1" },
  { label: "Estonia", value: "EE", flag: "🇪🇪", code: "+372" },
  { label: "Esuatini", value: "SZ", flag: "🇸🇿", code: "+268" },
  { label: "Etiopía", value: "ET", flag: "🇪🇹", code: "+251" },
  { label: "Filipinas", value: "PH", flag: "🇵🇭", code: "+63" },
  { label: "Finlandia", value: "FI", flag: "🇫🇮", code: "+358" },
  { label: "Fiyi", value: "FJ", flag: "🇫🇯", code: "+679" },
  { label: "Francia", value: "FR", flag: "🇫🇷", code: "+33" },
  { label: "Gabón", value: "GA", flag: "🇬🇦", code: "+241" },
  { label: "Gambia", value: "GM", flag: "🇬🇲", code: "+220" },
  { label: "Georgia", value: "GE", flag: "🇬🇪", code: "+995" },
  { label: "Ghana", value: "GH", flag: "🇬🇭", code: "+233" },
  { label: "Granada", value: "GD", flag: "🇬🇩", code: "+1-473" },
  { label: "Grecia", value: "GR", flag: "🇬🇷", code: "+30" },
  { label: "Guatemala", value: "GT", flag: "🇬🇹", code: "+502" },
  { label: "Guinea", value: "GN", flag: "🇬🇳", code: "+224" },
  { label: "Guinea-Bisáu", value: "GW", flag: "🇬🇼", code: "+245" },
  { label: "Guinea Ecuatorial", value: "GQ", flag: "🇬🇶", code: "+240" },
  { label: "Guyana", value: "GY", flag: "🇬🇾", code: "+592" },
  { label: "Haití", value: "HT", flag: "🇭🇹", code: "+509" },
  { label: "Honduras", value: "HN", flag: "🇭🇳", code: "+504" },
  { label: "Hungría", value: "HU", flag: "🇭🇺", code: "+36" },
  { label: "India", value: "IN", flag: "🇮🇳", code: "+91" },
  { label: "Indonesia", value: "ID", flag: "🇮🇩", code: "+62" },
  { label: "Irak", value: "IQ", flag: "🇮🇶", code: "+964" },
  { label: "Irlanda", value: "IE", flag: "🇮🇪", code: "+353" },
  { label: "Islandia", value: "IS", flag: "🇮🇸", code: "+354" },
  { label: "Islas Salomón", value: "SB", flag: "🇸🇧", code: "+677" },
  { label: "Israel", value: "IL", flag: "🇮🇱", code: "+972" },
  { label: "Italia", value: "IT", flag: "🇮🇹", code: "+39" },
  { label: "Jamaica", value: "JM", flag: "🇯🇲", code: "+1-876" },
  { label: "Japón", value: "JP", flag: "🇯🇵", code: "+81" },
  { label: "Jordania", value: "JO", flag: "🇯🇴", code: "+962" },
  { label: "Kazajistán", value: "KZ", flag: "🇰🇿", code: "+7" },
  { label: "Kenia", value: "KE", flag: "🇰🇪", code: "+254" },
  { label: "Kirguistán", value: "KG", flag: "🇰🇬", code: "+996" },
  { label: "Kiribati", value: "KI", flag: "🇰🇮", code: "+686" },
  { label: "Kuwait", value: "KW", flag: "🇰🇼", code: "+965" },
  { label: "Laos", value: "LA", flag: "🇱🇦", code: "+856" },
  { label: "Lesoto", value: "LS", flag: "🇱🇸", code: "+266" },
  { label: "Letonia", value: "LV", flag: "🇱🇻", code: "+371" },
  { label: "Líbano", value: "LB", flag: "🇱🇧", code: "+961" },
  { label: "Liberia", value: "LR", flag: "🇱🇷", code: "+231" },
  { label: "Libia", value: "LY", flag: "🇱🇾", code: "+218" },
  { label: "Liechtenstein", value: "LI", flag: "🇱🇮", code: "+423" },
  { label: "Lituania", value: "LT", flag: "🇱🇹", code: "+370" },
  { label: "Luxemburgo", value: "LU", flag: "🇱🇺", code: "+352" },
  { label: "Madagascar", value: "MG", flag: "🇲🇬", code: "+261" },
  { label: "Malasia", value: "MY", flag: "🇲🇾", code: "+60" },
  { label: "Malaui", value: "MW", flag: "🇲🇼", code: "+265" },
  { label: "Maldivas", value: "MV", flag: "🇲🇻", code: "+960" },
  { label: "Malí", value: "ML", flag: "🇲🇱", code: "+223" },
  { label: "Malta", value: "MT", flag: "🇲🇹", code: "+356" },
  { label: "Marruecos", value: "MA", flag: "🇲🇦", code: "+212" },
  { label: "Mauricio", value: "MU", flag: "🇲🇺", code: "+230" },
  { label: "Mauritania", value: "MR", flag: "🇲🇷", code: "+222" },
  { label: "México", value: "MX", flag: "🇲🇽", code: "+52" },
  { label: "Micronesia", value: "FM", flag: "🇫🇲", code: "+691" },
  { label: "Moldavia", value: "MD", flag: "🇲🇩", code: "+373" },
  { label: "Mónaco", value: "MC", flag: "🇲🇨", code: "+377" },
  { label: "Mongolia", value: "MN", flag: "🇲🇳", code: "+976" },
  { label: "Montenegro", value: "ME", flag: "🇲🇪", code: "+382" },
  { label: "Mozambique", value: "MZ", flag: "🇲🇿", code: "+258" },
  { label: "Namibia", value: "NA", flag: "🇳🇦", code: "+264" },
  { label: "Nauru", value: "NR", flag: "🇳🇷", code: "+674" },
  { label: "Nepal", value: "NP", flag: "🇳🇵", code: "+977" },
  { label: "Nicaragua", value: "NI", flag: "🇳🇮", code: "+505" },
  { label: "Níger", value: "NE", flag: "🇳🇪", code: "+227" },
  { label: "Nigeria", value: "NG", flag: "🇳🇬", code: "+234" },
  { label: "Noruega", value: "NO", flag: "🇳🇴", code: "+47" },
  { label: "Nueva Zelanda", value: "NZ", flag: "🇳🇿", code: "+64" },
  { label: "Omán", value: "OM", flag: "🇴🇲", code: "+968" },
  { label: "Países Bajos", value: "NL", flag: "🇳🇱", code: "+31" },
  { label: "Pakistán", value: "PK", flag: "🇵🇰", code: "+92" },
  { label: "Palaos", value: "PW", flag: "🇵🇼", code: "+680" },
  { label: "Panamá", value: "PA", flag: "🇵🇦", code: "+507" },
  { label: "Papúa Nueva Guinea", value: "PG", flag: "🇵🇬", code: "+675" },
  { label: "Paraguay", value: "PY", flag: "🇵🇾", code: "+595" },
  { label: "Perú", value: "PE", flag: "🇵🇪", code: "+51" },
  { label: "Polonia", value: "PL", flag: "🇵🇱", code: "+48" },
  { label: "Portugal", value: "PT", flag: "🇵🇹", code: "+351" },
  { label: "Puerto Rico", value: "PR", flag: "🇵🇷", code: "+1" },
  { label: "Rumania", value: "RO", flag: "🇷🇴", code: "+40" },
  { label: "Rusia", value: "RU", flag: "🇷🇺", code: "+7" },
  { label: "Ruanda", value: "RW", flag: "🇷🇼", code: "+250" },
  { label: "San Bartolomé", value: "BL", flag: "🇧🇱", code: "+590" },
  { label: "Santa Elena", value: "SH", flag: "🇸🇭", code: "+290" },
  { label: "San Cristóbal y Nieves", value: "KN", flag: "🇰🇳", code: "+1" },
  { label: "Santa Lucía", value: "LC", flag: "🇱🇨", code: "+1" },
  { label: "San Martín", value: "MF", flag: "🇲🇫", code: "+590" },
  { label: "San Pedro y Miquelón", value: "PM", flag: "🇵🇲", code: "+508" },
  { label: "San Vicente y las Granadinas", value: "VC", flag: "🇻🇨", code: "+1" },
  { label: "Samoa", value: "WS", flag: "🇼🇸", code: "+685" },
  { label: "San Marino", value: "SM", flag: "🇸🇲", code: "+378" },
  { label: "Santo Tomé y Príncipe", value: "ST", flag: "🇸🇹", code: "+239" },
  { label: "Senegal", value: "SN", flag: "🇸🇳", code: "+221" },
  { label: "Serbia", value: "RS", flag: "🇷🇸", code: "+381" },
  { label: "Seychelles", value: "SC", flag: "🇸🇨", code: "+248" },
  { label: "Sierra Leona", value: "SL", flag: "🇸🇱", code: "+232" },
  { label: "Singapur", value: "SG", flag: "🇸🇬", code: "+65" },
  { label: "Sint Maarten", value: "SX", flag: "🇸🇽", code: "+1" },
  { label: "Somalia", value: "SO", flag: "🇸🇴", code: "+252" },
  { label: "Sudáfrica", value: "ZA", flag: "🇿🇦", code: "+27" },
  { label: "Islas Georgias del Sur y Sandwich del Sur", value: "GS", flag: "🇬🇸", code: "+500" },
  { label: "Sudán del Sur", value: "SS", flag: "🇸🇸", code: "+211" },
  { label: "Sri Lanka", value: "LK", flag: "🇱🇰", code: "+94" },
  { label: "Sudán", value: "SD", flag: "🇸🇩", code: "+249" },
  { label: "Surinam", value: "SR", flag: "🇸🇷", code: "+597" },
  { label: "Svalbard y Jan Mayen", value: "SJ", flag: "🇸🇯", code: "+47" },
  { label: "Suecia", value: "SE", flag: "🇸🇪", code: "+46" },
  { label: "Suiza", value: "CH", flag: "🇨🇭", code: "+41" },
  { label: "Siria", value: "SY", flag: "🇸🇾", code: "+963" },
  { label: "Taiwán", value: "TW", flag: "🇹🇼", code: "+886" },
  { label: "Tayikistán", value: "TJ", flag: "🇹🇯", code: "+992" },
  { label: "Tanzania", value: "TZ", flag: "🇹🇿", code: "+255" },
  { label: "Tailandia", value: "TH", flag: "🇹🇭", code: "+66" },
  { label: "Timor Oriental", value: "TL", flag: "🇹🇱", code: "+670" },
  { label: "Togo", value: "TG", flag: "🇹🇬", code: "+228" },
  { label: "Tokelau", value: "TK", flag: "🇹🇰", code: "+690" },
  { label: "Tonga", value: "TO", flag: "🇹🇴", code: "+676" },
  { label: "Trinidad y Tobago", value: "TT", flag: "🇹🇹", code: "+1" },
  { label: "Túnez", value: "TN", flag: "🇹🇳", code: "+216" },
  { label: "Turquía", value: "TR", flag: "🇹🇷", code: "+90" },
  { label: "Turkmenistán", value: "TM", flag: "🇹🇲", code: "+993" },
  { label: "Islas Turcas y Caicos", value: "TC", flag: "🇹🇨", code: "+1" },
  { label: "Tuvalu", value: "TV", flag: "🇹🇻", code: "+688" },
  { label: "Uganda", value: "UG", flag: "🇺🇬", code: "+256" },
  { label: "Ucrania", value: "UA", flag: "🇺🇦", code: "+380" },
  { label: "Reino Unido", value: "GB", flag: "🇬🇧", code: "+44" },
  { label: "Uruguay", value: "UY", flag: "🇺🇾", code: "+598" },
  { label: "Uzbekistán", value: "UZ", flag: "🇺🇿", code: "+998" },
  { label: "Vanuatu", value: "VU", flag: "🇻🇺", code: "+678" },
  { label: "Ciudad del Vaticano", value: "VA", flag: "🇻🇦", code: "+379" },
  { label: "Venezuela", value: "VE", flag: "🇻🇪", code: "+58" },
  { label: "Vietnam", value: "VN", flag: "🇻🇳", code: "+84" },
  { label: "Wallis y Futuna", value: "WF", flag: "🇼🇫", code: "+681" },
  { label: "Sahara Occidental", value: "EH", flag: "🇪🇭", code: "+212" },
  { label: "Yemen", value: "YE", flag: "🇾🇪", code: "+967" },
  { label: "Zambia", value: "ZM", flag: "🇿🇲", code: "+260" },
  { label: "Zimbabue", value: "ZW", flag: "🇿🇼", code: "+263" },
];
