export interface Country {
  label: string;
  value: string;
  flag: string;
}

export const countries: Country[] = [
  { label: "Afganistán", value: "AF", flag: "🇦🇫" },
  { label: "Albania", value: "AL", flag: "🇦🇱" },
  { label: "Alemania", value: "DE", flag: "🇩🇪" },
  { label: "Andorra", value: "AD", flag: "🇦🇩" },
  { label: "Angola", value: "AO", flag: "🇦🇴" },
  { label: "Antigua y Barbuda", value: "AG", flag: "🇦🇬" },
  { label: "Arabia Saudita", value: "SA", flag: "🇸🇦" },
  { label: "Argelia", value: "DZ", flag: "🇩🇿" },
  { label: "Argentina", value: "AR", flag: "🇦🇷" },
  { label: "Armenia", value: "AM", flag: "🇦🇲" },
  { label: "Australia", value: "AU", flag: "🇦🇺" },
  { label: "Austria", value: "AT", flag: "🇦🇹" },
  { label: "Azerbaiyán", value: "AZ", flag: "🇦🇿" },
  { label: "Bahamas", value: "BS", flag: "🇧🇸" },
  { label: "Bangladés", value: "BD", flag: "🇧🇩" },
  { label: "Barbados", value: "BB", flag: "🇧🇧" },
  { label: "Baréin", value: "BH", flag: "🇧🇭" },
  { label: "Belice", value: "BZ", flag: "🇧🇿" },
  { label: "Benín", value: "BJ", flag: "🇧🇯" },
  { label: "Bielorrusia", value: "BY", flag: "🇧🇾" },
  { label: "Birmania", value: "MM", flag: "🇲🇲" },
  { label: "Bolivia", value: "BO", flag: "🇧🇴" },
  { label: "Bosnia y Herzegovina", value: "BA", flag: "🇧🇦" },
  { label: "Botsuana", value: "BW", flag: "🇧🇼" },
  { label: "Brasil", value: "BR", flag: "🇧🇷" },
  { label: "Brunéi", value: "BN", flag: "🇧🇳" },
  { label: "Bulgaria", value: "BG", flag: "🇧🇬" },
  { label: "Burkina Faso", value: "BF", flag: "🇧🇫" },
  { label: "Burundi", value: "BI", flag: "🇧🇮" },
  { label: "Bután", value: "BT", flag: "🇧🇹" },
  { label: "Cabo Verde", value: "CV", flag: "🇨🇻" },
  { label: "Camboya", value: "KH", flag: "🇰🇭" },
  { label: "Camerún", value: "CM", flag: "🇨🇲" },
  { label: "Canadá", value: "CA", flag: "🇨🇦" },
  { label: "Catar", value: "QA", flag: "🇶🇦" },
  { label: "Chad", value: "TD", flag: "🇹🇩" },
  { label: "Chile", value: "CL", flag: "🇨🇱" },
  { label: "China", value: "CN", flag: "🇨🇳" },
  { label: "Chipre", value: "CY", flag: "🇨🇾" },
  { label: "Colombia", value: "CO", flag: "🇨🇴" },
  { label: "Comoras", value: "KM", flag: "🇰🇲" },
  { label: "Corea del Norte", value: "KP", flag: "🇰🇵" },
  { label: "Corea del Sur", value: "KR", flag: "🇰🇷" },
  { label: "Costa de Marfil", value: "CI", flag: "🇨🇮" },
  { label: "Costa Rica", value: "CR", flag: "🇨🇷" },
  { label: "Croacia", value: "HR", flag: "🇭🇷" },
  { label: "Cuba", value: "CU", flag: "🇨🇺" },
  { label: "Dinamarca", value: "DK", flag: "🇩🇰" },
  { label: "Dominica", value: "DM", flag: "🇩🇲" },
  { label: "Ecuador", value: "EC", flag: "🇪🇨" },
  { label: "Egipto", value: "EG", flag: "🇪🇬" },
  { label: "El Salvador", value: "SV", flag: "🇸🇻" },
  { label: "Emiratos Árabes Unidos", value: "AE", flag: "🇦🇪" },
  { label: "Eritrea", value: "ER", flag: "🇪🇷" },
  { label: "Eslovaquia", value: "SK", flag: "🇸🇰" },
  { label: "Eslovenia", value: "SI", flag: "🇸🇮" },
  { label: "España", value: "ES", flag: "🇪🇸" },
  { label: "Estados Unidos", value: "US", flag: "🇺🇸" },
  { label: "Estonia", value: "EE", flag: "🇪🇪" },
  { label: "Esuatini", value: "SZ", flag: "🇸🇿" },
  { label: "Etiopía", value: "ET", flag: "🇪🇹" },
  { label: "Filipinas", value: "PH", flag: "🇵🇭" },
  { label: "Finlandia", value: "FI", flag: "🇫🇮" },
  { label: "Fiyi", value: "FJ", flag: "🇫🇯" },
  { label: "Francia", value: "FR", flag: "🇫🇷" },
  { label: "Gabón", value: "GA", flag: "🇬🇦" },
  { label: "Gambia", value: "GM", flag: "🇬🇲" },
  { label: "Georgia", value: "GE", flag: "🇬🇪" },
  { label: "Ghana", value: "GH", flag: "🇬🇭" },
  { label: "Granada", value: "GD", flag: "🇬🇩" },
  { label: "Grecia", value: "GR", flag: "🇬🇷" },
  { label: "Guatemala", value: "GT", flag: "🇬🇹" },
  { label: "Guinea", value: "GN", flag: "🇬🇳" },
  { label: "Guinea-Bisáu", value: "GW", flag: "🇬🇼" },
  { label: "Guinea Ecuatorial", value: "GQ", flag: "🇬🇶" },
  { label: "Guyana", value: "GY", flag: "🇬🇾" },
  { label: "Haití", value: "HT", flag: "🇭🇹" },
  { label: "Honduras", value: "HN", flag: "🇭🇳" },
  { label: "Hungría", value: "HU", flag: "🇭🇺" },
  { label: "India", value: "IN", flag: "🇮🇳" },
  { label: "Indonesia", value: "ID", flag: "🇮🇩" },
  { label: "Irak", value: "IQ", flag: "🇮🇶" },
  { label: "Irlanda", value: "IE", flag: "🇮🇪" },
  { label: "Islandia", value: "IS", flag: "🇮🇸" },
  { label: "Islas Salomón", value: "SB", flag: "🇸🇧" },
  { label: "Israel", value: "IL", flag: "🇮🇱" },
  { label: "Italia", value: "IT", flag: "🇮🇹" },
  { label: "Jamaica", value: "JM", flag: "🇯🇲" },
  { label: "Japón", value: "JP", flag: "🇯🇵" },
  { label: "Jordania", value: "JO", flag: "🇯🇴" },
  { label: "Kazajistán", value: "KZ", flag: "🇰🇿" },
  { label: "Kenia", value: "KE", flag: "🇰🇪" },
  { label: "Kirguistán", value: "KG", flag: "🇰🇬" },
  { label: "Kiribati", value: "KI", flag: "🇰🇮" },
  { label: "Kuwait", value: "KW", flag: "🇰🇼" },
  { label: "Laos", value: "LA", flag: "🇱🇦" },
  { label: "Lesoto", value: "LS", flag: "🇱🇸" },
  { label: "Letonia", value: "LV", flag: "🇱🇻" },
  { label: "Líbano", value: "LB", flag: "🇱🇧" },
  { label: "Liberia", value: "LR", flag: "🇱🇷" },
  { label: "Libia", value: "LY", flag: "🇱🇾" },
  { label: "Liechtenstein", value: "LI", flag: "🇱🇮" },
  { label: "Lituania", value: "LT", flag: "🇱🇹" },
  { label: "Luxemburgo", value: "LU", flag: "🇱🇺" },
  { label: "Madagascar", value: "MG", flag: "🇲🇬" },
  { label: "Malasia", value: "MY", flag: "🇲🇾" },
  { label: "Malaui", value: "MW", flag: "🇲🇼" },
  { label: "Maldivas", value: "MV", flag: "🇲🇻" },
  { label: "Malí", value: "ML", flag: "🇲🇱" },
  { label: "Malta", value: "MT", flag: "🇲🇹" },
  { label: "Marruecos", value: "MA", flag: "🇲🇦" },
  { label: "Mauricio", value: "MU", flag: "🇲🇺" },
  { label: "Mauritania", value: "MR", flag: "🇲🇷" },
  { label: "México", value: "MX", flag: "🇲🇽" },
  { label: "Micronesia", value: "FM", flag: "🇫🇲" },
  { label: "Moldavia", value: "MD", flag: "🇲🇩" },
  { label: "Mónaco", value: "MC", flag: "🇲🇨" },
  { label: "Mongolia", value: "MN", flag: "🇲🇳" },
  { label: "Montenegro", value: "ME", flag: "🇲🇪" },
  { label: "Mozambique", value: "MZ", flag: "🇲🇿" },
  { label: "Namibia", value: "NA", flag: "🇳🇦" },
  { label: "Nauru", value: "NR", flag: "🇳🇷" },
  { label: "Nepal", value: "NP", flag: "🇳🇵" },
  { label: "Nicaragua", value: "NI", flag: "🇳🇮" },
  { label: "Níger", value: "NE", flag: "🇳🇪" },
  { label: "Nigeria", value: "NG", flag: "🇳🇬" },
  { label: "Noruega", value: "NO", flag: "🇳🇴" },
  { label: "Nueva Zelanda", value: "NZ", flag: "🇳🇿" },
  { label: "Omán", value: "OM", flag: "🇴🇲" },
  { label: "Países Bajos", value: "NL", flag: "🇳🇱" },
  { label: "Pakistán", value: "PK", flag: "🇵🇰" },
  { label: "Palaos", value: "PW", flag: "🇵🇼" },
  { label: "Panamá", value: "PA", flag: "🇵🇦" },
  { label: "Papúa Nueva Guinea", value: "PG", flag: "🇵🇬" },
  { label: "Paraguay", value: "PY", flag: "🇵🇾" },
  { label: "Perú", value: "PE", flag: "🇵🇪" },
  { label: "Polonia", value: "PL", flag: "🇵🇱" },
  { label: "Portugal", value: "PT", flag: "🇵🇹" },
  { label: "Puerto Rico", value: "PR", flag: "🇵🇷" },
  { label: "Rumania", value: "RO", flag: "🇷🇴" },
  { label: "Rusia", value: "RU", flag: "🇷🇺" },
  { label: "Ruanda", value: "RW", flag: "🇷🇼" },
  { label: "San Bartolomé", value: "BL", flag: "🇧🇱" },
  { label: "Santa Elena", value: "SH", flag: "🇸🇭" },
  { label: "San Cristóbal y Nieves", value: "KN", flag: "🇰🇳" },
  { label: "Santa Lucía", value: "LC", flag: "🇱🇨" },
  { label: "San Martín", value: "MF", flag: "🇲🇫" },
  { label: "San Pedro y Miquelón", value: "PM", flag: "🇵🇲" },
  { label: "San Vicente y las Granadinas", value: "VC", flag: "🇻🇨" },
  { label: "Samoa", value: "WS", flag: "🇼🇸" },
  { label: "San Marino", value: "SM", flag: "🇸🇲" },
  { label: "Santo Tomé y Príncipe", value: "ST", flag: "🇸🇹" },
  { label: "Senegal", value: "SN", flag: "🇸🇳" },
  { label: "Serbia", value: "RS", flag: "🇷🇸" },
  { label: "Seychelles", value: "SC", flag: "🇸🇨" },
  { label: "Sierra Leona", value: "SL", flag: "🇸🇱" },
  { label: "Singapur", value: "SG", flag: "🇸🇬" },
  { label: "Sint Maarten", value: "SX", flag: "🇸🇽" },
  { label: "Somalia", value: "SO", flag: "🇸🇴" },
  { label: "Sudáfrica", value: "ZA", flag: "🇿🇦" },
  { label: "Islas Georgias del Sur y Sandwich del Sur", value: "GS", flag: "🇬🇸" },
  { label: "Sudán del Sur", value: "SS", flag: "🇸🇸" },
  { label: "Sri Lanka", value: "LK", flag: "🇱🇰" },
  { label: "Sudán", value: "SD", flag: "🇸🇩" },
  { label: "Surinam", value: "SR", flag: "🇸🇷" },
  { label: "Svalbard y Jan Mayen", value: "SJ", flag: "🇸🇯" },
  { label: "Suecia", value: "SE", flag: "🇸🇪" },
  { label: "Suiza", value: "CH", flag: "🇨🇭" },
  { label: "Siria", value: "SY", flag: "🇸🇾" },
  { label: "Taiwán", value: "TW", flag: "🇹🇼" },
  { label: "Tayikistán", value: "TJ", flag: "🇹🇯" },
  { label: "Tanzania", value: "TZ", flag: "🇹🇿" },
  { label: "Tailandia", value: "TH", flag: "🇹🇭" },
  { label: "Timor Oriental", value: "TL", flag: "🇹🇱" },
  { label: "Togo", value: "TG", flag: "🇹🇬" },
  { label: "Tokelau", value: "TK", flag: "🇹🇰" },
  { label: "Tonga", value: "TO", flag: "🇹🇴" },
  { label: "Trinidad y Tobago", value: "TT", flag: "🇹🇹" },
  { label: "Túnez", value: "TN", flag: "🇹🇳" },
  { label: "Turquía", value: "TR", flag: "🇹🇷" },
  { label: "Turkmenistán", value: "TM", flag: "🇹🇲" },
  { label: "Islas Turcas y Caicos", value: "TC", flag: "🇹🇨" },
  { label: "Tuvalu", value: "TV", flag: "🇹🇻" },
  { label: "Uganda", value: "UG", flag: "🇺🇬" },
  { label: "Ucrania", value: "UA", flag: "🇺🇦" },
  { label: "Reino Unido", value: "GB", flag: "🇬🇧" },
  { label: "Uruguay", value: "UY", flag: "🇺🇾" },
  { label: "Uzbekistán", value: "UZ", flag: "🇺🇿" },
  { label: "Vanuatu", value: "VU", flag: "🇻🇺" },
  { label: "Ciudad del Vaticano", value: "VA", flag: "🇻🇦" },
  { label: "Venezuela", value: "VE", flag: "🇻🇪" },
  { label: "Vietnam", value: "VN", flag: "🇻🇳" },
  { label: "Wallis y Futuna", value: "WF", flag: "🇼🇫" },
  { label: "Sahara Occidental", value: "EH", flag: "🇪🇭" },
  { label: "Yemen", value: "YE", flag: "🇾🇪" },
  { label: "Zambia", value: "ZM", flag: "🇿🇲" },
  { label: "Zimbabue", value: "ZW", flag: "🇿🇼" },
];
